about_us.html
blog.html
branding_assets.html
calendar.html
dev_meetings.html
ech_youtube.html
eip_resources.html
index.html
js/script2.js
network_upgrades.html
surveys.html

changes made

---

about_us.html
blog.html
branding_assets.html
calendar.html
dev_meetings.html
ech_youtube.html
eip_resources.html
index.html
js/script2.js
js/script3.js
network_upgrades.html
surveys.html

1. Added version numbering on all footer pages  - v1.0.3
2. Home: tv youtube updates 
-  Latest video: Working Group: Address Space Extension Meeting # 5
-  PEEPanEIP video: PEEPanEIP #40 - A Brief History of Ethereum's Future with Ben Edgington

Version 1.0.3

---

about_us.html
blog.html
branding_assets.html
calendar.html
dev_meetings.html
ech_youtube.html
eip_resources.html
index.html
js/script2.js
js/script3.js
network_upgrades.html
surveys.html

Hi Team,
Updated ver 1.1.0 to ver 1.2.0 
Updates:
1. Added contents in eip_resources page:
EIP-3540: EVM Object Format (EOF) v1
Resources
EIP-3540
PEEPanEIP-3540 & EIP-3541 with Alex B., Paweł B., Andrei M.
Discussion
Fellowship of Ethereum Magicians
EIP-3675: Upgrade consensus to Proof-of-Stake
Resources
EIP-3675
PEEPanEIP-3675: Upgrade consensus to Proof-of-Stake with Mikhail Kalinin
Charting The Path To Proof of Stake Ethereum by ConsenSys
Discussion
Fellowship of Ethereum Magicians
2. Updated all videos in home page as well.
Thank you,
Unvetica

ver 1.1.0 -> ver 1.2.0

---

about_us.html
blog.html
branding_assets.html
calendar.html
css/main.css
dev_meetings.html
ech_youtube.html
eip_resources.html
index.html
js/script2.js
js/script3.js
network_upgrades.html
surveys.html

Hi Team,
Ver 1.3.0 updates.
1. Home page - added buttons
2. Additional Resources - Verkle trie
Additional Adds.
1. Homepage videos are now updated but not yet dynamic
To follow: 
1. Coding in progress. Will update homepage videos to dynamic.
2. Will be back soon page.
3. .html removal will be a server .htaccess update @michaelgiesen kindly take a look at this
https://perishablepress.com/change-file-extension-htaccess/
Thanks,
Jerik | Unvetica Team

ver 1.2.0 -> ver 1.3.0

---

.htaccess

updated the .htaccess file, the previous one might confuse the server and return an error.

Updated the .htaccess

---

.htaccess
about/index.html
blog/index.html
branding/index.html
calendar/index.html
dev_meetings/index.html
ech_youtube/index.html
eip_resources/index.html
index.html
network_upgrades/index.html
surveys/index.html

ver1.3.2 updates
1. .htaccess final fix. 
2. Home page update: Read our journey with the Ethereum ecosystem - Review 2021 mid year 
3. Survey page update: Move "Ethereum blockchain users and developers research" to Completed section

ver 1.3.1 -> 1.3.2

---

dev_meetings/index.html

Hi Team,
dev_meetings page is now fixed.

fixed the dev_meetings page 

---

the_merge.html

For Issue #238 in pm repo: [View issue](https://github.com/ethereum-cat-herders/PM/issues/238)
This is a WIP that still needs some additional resources, especially relevant write-ups, GitHub links, and more content/diagrams. Please feel free to edit and add more resources that should be included in this page. #

New page for curated resources on "The Merge"

---

home.html
index.html

This is just a quick fix to display the merge page correctly. It shows the ".html" which will need to be resolved in the future.

Redirect link directly to html page

---

the_merge/index.html

Hi Team,
Fixed minor alignments on The Merge page.
Thanks,
Jerik | Unvetica Team

The Merge page ui minor alignment changes

---

blog/index.html
the_merge/index.html

Added links for EIP-4844 and Kiln Merge Testnet

Update the_merge page

---

dev_meetings/index.html

updated link for all core dev meetings on "https://www.ethereumcatherders.com/dev_meetings/"

Updated dev_meetings

---

Backsoon.html
README.md
css/main.css
home.html
index.html
js/script2.js
podcasts/index.html

1. Changed logic for meetings on home page
2. Fixed the routes for website deployment

Code upload

---

eip_resources/index.html
index.html
shanghai_upgrade/index.html

Fixed 
1. Issue 76
2. Issue 77
3. Issue 79

Fixed Issues 76 77 and 79

---

README.md
home.html
index.html
shanghai_upgrade/index.html

1. Fixed home page button layout
2. Fixes in shanghai page

Fixes in catherders

---

home.html
index.html

Fixed typo on homepage to "Shanghai"
- [Fixes #86]

Patch: typo fix

---

dencun/index.html
index.html

Fixed homepage link to dencun to correct URL and changed Updates section in Dencun page to mm/yyyy.

Minor fixes to dencun link and updates

---

dencun/index.html

Added devnet 9 to the updates section and the dencun testing overview to resources.

Update Dencun page: Add Devnet 9 specs and Dencun testing overview

---

dencun/index.html
podcast/index.html

Following changes made:
- Add devnet 10 to the updates section in Dencun page
- Rearrange podcasts so Spotify and Apple Podcast are top row

Add devnet 10 and reorg podcast platforms

---

dencun/index.html

Added Devnet 11 to the updates section in Dencun page.

Add devnet v11 to dencun

---

README.md

Thought it would be helpful to have the link to the site in the readme for convenience

feat: Adds link to site in readme

---

network_upgrades/index.html

Would resolve https://github.com/ethereum-cat-herders/ech-website-v2/issues/124 if merged

fix: Corrects missing dates in Network Upgrade cards

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Would resolve https://github.com/ethereum-cat-herders/ech-website-v2/issues/129 if merged

feat: Adds default bug & feature request templates
